<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="suresh-pc" name="Default test" tests="1" failures="1" timestamp="30 Jun 2016 10:25:31 GMT" time="77.193" errors="0">
  <testcase name="MailWithAttachemnt" time="77.181" classname="Sikuli_WindowsConcpets.Sukuli_Mail_Attachment">
    <failure type="org.sikuli.script.FindFailed" message="can not find P(C:\WorkSpaces\Dheera\WebDriverConceptsOnly\Sikuli_Images\Gmailsubject.png) S: 0.7 on the screen.">
      <![CDATA[FindFailed: can not find P(C:\WorkSpaces\Dheera\WebDriverConceptsOnly\Sikuli_Images\Gmailsubject.png) S: 0.7 on the screen.
  Line 1574, in file Region.java

	at org.sikuli.script.Region.handleFindFailed(Region.java:1574)
	at org.sikuli.script.Region.wait(Region.java:1682)
	at org.sikuli.script.Region.find(Region.java:1590)
	at org.sikuli.script.Region.getLocationFromTarget(Region.java:1991)
	at org.sikuli.script.Region.click(Region.java:2197)
	at org.sikuli.script.Region.keyin(Region.java:2718)
	at org.sikuli.script.Region.type(Region.java:2678)
	at Sikuli_WindowsConcpets.Sukuli_Mail_Attachment.MailWithAttachemnt(Sukuli_Mail_Attachment.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- MailWithAttachemnt -->
</testsuite> <!-- Default test -->
